In [2]:
# DAV Experiment 4
# Data Preprocessing: Missing Value Imputation and Categorical Encoding

import pandas as pd
import numpy as np
import os

# Step 1: Load the dataset
file_name = "housing_raw.xlsx"

if not os.path.exists(file_name):
    raise FileNotFoundError(
        "housing_raw.xlsx not found. Upload the Excel file "
        "to the same folder as this Jupyter Notebook."
    )

df = pd.read_excel(file_name)

print("ORIGINAL DATASET")
display(df.head())

print("\nDataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values Before Preprocessing:")
print(df.isnull().sum())


# Step 2: Identify numerical and categorical columns
numeric_cols = df.select_dtypes(
    include=np.number
).columns.tolist()

categorical_cols = df.select_dtypes(
    include=["object", "category", "string"]
).columns.tolist()


# Step 3: Mean Imputation
mean_df = df.copy()

for col in numeric_cols:
    if mean_df[col].notna().any():
        mean_df[col] = mean_df[col].fillna(
            mean_df[col].mean()
        )

print("\nDATASET AFTER MEAN IMPUTATION")
display(mean_df.head())


# Step 4: Median Imputation
median_df = df.copy()

for col in numeric_cols:
    if median_df[col].notna().any():
        median_df[col] = median_df[col].fillna(
            median_df[col].median()
        )

print("\nDATASET AFTER MEDIAN IMPUTATION")
display(median_df.head())


# Step 5: Forward Fill
ffill_df = df.copy()
ffill_df = ffill_df.ffill()

print("\nDATASET AFTER FORWARD FILL")
display(ffill_df.head())


# Step 6: Create the final cleaned dataset
clean_df = df.copy()

# Fill missing numerical values using median
for col in numeric_cols:
    if clean_df[col].notna().any():
        clean_df[col] = clean_df[col].fillna(
            clean_df[col].median()
        )

# Fill missing categorical values using mode
for col in categorical_cols:
    mode_values = clean_df[col].mode(dropna=True)

    if not mode_values.empty:
        clean_df[col] = clean_df[col].fillna(
            mode_values.iloc[0]
        )
    else:
        clean_df[col] = clean_df[col].fillna("Unknown")


# Step 7: Encode categorical variables
clean_df = pd.get_dummies(
    clean_df,
    columns=categorical_cols,
    dtype=int
)

print("\nDATASET AFTER CATEGORICAL ENCODING")
display(clean_df.head())


# Step 8: Check missing values after preprocessing
print("\nMissing Values After Preprocessing:")
print(clean_df.isnull().sum())


# Step 9: Save the processed datasets
clean_df.to_csv(
    "housing_preprocessed.csv",
    index=False
)

clean_df.to_excel(
    "housing_preprocessed.xlsx",
    index=False
)

# Save the individual imputation results
mean_df.to_csv("housing_mean_imputation.csv", index=False)
median_df.to_csv("housing_median_imputation.csv", index=False)
ffill_df.to_csv("housing_forward_fill.csv", index=False)

print("\nPREPROCESSING COMPLETED SUCCESSFULLY!")
print("Generated files:")
print("1. housing_preprocessed.csv")
print("2. housing_preprocessed.xlsx")
print("3. housing_mean_imputation.csv")
print("4. housing_median_imputation.csv")
print("5. housing_forward_fill.csv")

ORIGINAL DATASET

   Area Rooms Age   Location         Price Premium
0   800     1  12   Hubballi       3540000      No
1     -     1  18        NaN       5980000      No
2  2750     5  11   Hubballi   Rs. 9170000     Yes
3  2500     4  22  Bengaluru  Rs. 14190000    true
4   800     2  13     Hassan       3010000      No

Dataset Shape: (234, 6)

Column Names:
['Area', 'Rooms', 'Age', 'Location', 'Price', 'Premium']

Missing Values Before Preprocessing:
Area        12
Rooms        5
Age         12
Location     6
Price        7
Premium      5
dtype: int64

DATASET AFTER MEAN IMPUTATION

   Area Rooms Age   Location         Price Premium
0   800     1  12   Hubballi       3540000      No
1     -     1  18        NaN       5980000      No
2  2750     5  11   Hubballi   Rs. 9170000     Yes
3  2500     4  22  Bengaluru  Rs. 14190000    true
4   800     2  13     Hassan       3010000      No

DATASET AFTER MEDIAN IMPUTATION

   Area Rooms Age   Location         Price Premium
0   800     1  12   Hubballi       3540000      No
1     -     1  18        NaN       5980000      No
2  2750     5  11   Hubballi   Rs. 9170000     Yes
3  2500     4  22  Bengaluru  Rs. 14190000    true
4   800     2  13     Hassan       3010000      No

DATASET AFTER FORWARD FILL

   Area Rooms Age   Location         Price Premium
0   800     1  12   Hubballi       3540000      No
1     -     1  18   Hubballi       5980000      No
2  2750     5  11   Hubballi   Rs. 9170000     Yes
3  2500     4  22  Bengaluru  Rs. 14190000    true
4   800     2  13     Hassan       3010000      No

DATASET AFTER CATEGORICAL ENCODING

,Area_-1200,Area_600,Area_650,Area_700,Area_750,Area_800,Area_850,Area_900,Area_950,Area_1000,...,Premium_No,Premium_TRUE,Premium_Y,Premium_YES,Premium_Yes,Premium_false,Premium_no,Premium_true,Premium_yes,Premium_—
0,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

Missing Values After Preprocessing:
Area_-1200       0
Area_600         0
Area_650         0
Area_700         0
Area_750         0
                ..
Premium_false    0
Premium_no       0
Premium_true     0
Premium_yes      0
Premium_—        0
Length: 383, dtype: int64

PREPROCESSING COMPLETED SUCCESSFULLY!
Generated files:
1. housing_preprocessed.csv
2. housing_preprocessed.xlsx
3. housing_mean_imputation.csv
4. housing_median_imputation.csv
5. housing_forward_fill.csv